// Generated by build/write_buildflag_header.py
// From "//url:url_features"

#ifndef URL_URL_FEATURES_H_
#define URL_URL_FEATURES_H_

#include "build/buildflag.h"

#define BUILDFLAG_INTERNAL_USE_PLATFORM_ICU_ALTERNATIVES() (1)

#endif  // URL_URL_FEATURES_H_
