// Generated by build/write_buildflag_header.py
// From "//ios/net:ios_net_features"

#ifndef IOS_NET_IOS_NET_FEATURES_H_
#define IOS_NET_IOS_NET_FEATURES_H_

#include "build/buildflag.h"

#define BUILDFLAG_INTERNAL_CRONET_BUILD() (1)

#endif  // IOS_NET_IOS_NET_FEATURES_H_
